import { theme } from "../styles/theme";

// ── category definitions ──────────────────────────────────────────────────────
export const CATEGORIES = {
  all:       { label: "All",        icon: "✦",  color: theme.navy    },
  screening: { label: "Screenings", icon: "🩺", color: "#1A3A6B"    },
  vaccine:   { label: "Vaccines",   icon: "💉", color: "#2D7DD2"    },
  lifestyle: { label: "Lifestyle",  icon: "🥗", color: "#C07800"    },
};

// ── not verified URLs 
export const TOPIC_URLS = {
  "blood pressure":    "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-your-blood-pressure-checked",
  "diabetes":          "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-tested-for-diabetes",
  "cholesterol":       "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-your-cholesterol-checked",
  "colorectal":        "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-colorectal-cancer",
  "colon":             "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-for-colorectal-cancer",
  "breast cancer":     "https://odphp.health.gov/myhealthfinder/health-conditions/cancer/get-screened-breast-cancer",
  "mammogram":         "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-a-mammogram",
  "cervical":          "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-cervical-cancer",
  "pap":               "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-for-cervical-cancer",
  "lung cancer":       "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-for-lung-cancer",
  "osteoporosis":      "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-a-bone-density-test",
  "bone density":      "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-a-bone-density-test",
  "depression":        "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-for-depression",
  "hiv":               "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-tested-for-hiv",
  "hepatitis c":       "https://odphp.health.gov/myhealthfinder/doctor-visits/talking-doctor/hepatitis-c-screening-questions-doctor",
  "hepatitis":         "https://odphp.health.gov/myhealthfinder/doctor-visits/talking-doctor/hepatitis-c-screening-questions-doctor",
  "skin cancer":       "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/talk-to-your-doctor-about-skin-cancer",
  "vision":            "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-your-eyes-tested",
  "eye":               "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-your-eyes-tested",
  "hearing":           "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-your-hearing-checked",
  "flu":               "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-flu-vaccine",
  "influenza":         "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-flu-vaccine",
  "covid":             "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-covid-19-vaccine",
  "pneumonia":         "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-pneumococcal-vaccine",
  "pneumococcal":      "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-pneumococcal-vaccine",
  "shingles":          "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-shingles-vaccine",
  "tdap":              "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-tdap-vaccine",
  "tetanus":           "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-a-tdap-vaccine",
  "hpv":               "https://odphp.health.gov/myhealthfinder/doctor-visits/vaccines/get-the-hpv-vaccine",
  "physical activity": "https://odphp.health.gov/myhealthfinder/health-topics/physical-activity/get-active",
  "exercise":          "https://odphp.health.gov/myhealthfinder/health-topics/physical-activity/get-active",
  "healthy eating":    "https://odphp.health.gov/myhealthfinder/health-topics/nutrition/eat-healthy",
  "nutrition":         "https://odphp.health.gov/myhealthfinder/health-topics/nutrition/eat-healthy",
  "weight":            "https://odphp.health.gov/myhealthfinder/health-topics/weight/maintain-a-healthy-weight",
  "smoking":           "https://odphp.health.gov/myhealthfinder/health-topics/tobacco/quit-smoking",
  "tobacco":           "https://odphp.health.gov/myhealthfinder/health-topics/tobacco/quit-smoking",
  "alcohol":           "https://odphp.health.gov/myhealthfinder/health-conditions/heart-health/drink-alcohol-only-moderation",
  "stress":            "https://odphp.health.gov/myhealthfinder/health-topics/mental-health-and-relationships/manage-stress",
  "mental health":     "https://odphp.health.gov/myhealthfinder/health-topics/mental-health-and-relationships/mental-health",
  "prenatal":          "https://odphp.health.gov/myhealthfinder/pregnancy/doctor-and-midwife-visits/prenatal-care",
  "folic acid":        "https://odphp.health.gov/myhealthfinder/pregnancy/nutrition-and-physical-activity/folic-acid",
  "prostate":          "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/talk-to-your-doctor-about-prostate-cancer-screening",
  "abdominal aortic":  "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-for-abdominal-aortic-aneurysm",
  "aortic aneurysm":   "https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened-for-abdominal-aortic-aneurysm",
  "sleep":             "https://odphp.health.gov/myhealthfinder/health-topics/sleep/get-enough-sleep",
  "dental":            "https://odphp.health.gov/myhealthfinder/doctor-visits/regular-checkups/take-care-of-your-teeth-and-gums",
  "teeth":             "https://odphp.health.gov/myhealthfinder/doctor-visits/regular-checkups/take-care-of-your-teeth-and-gums",
};
